version: '3'

services:
  necesse-game-server:
    build:
      context: game-server
      args:
        - SERVER_DOWNLOAD_URL=$SERVER_DOWNLOAD_URL
    restart: unless-stopped
    volumes:
      - ./save-data:/root/.config/Necesse
    ports:
      - "14159:14159"
    command: -world $WORLD_NAME
